[base]
path = "/data/users/mhance/SUSY"
output = "SUSY_1938"
template = "{{PWD}}/templates/sleptons.toml"
process_path = "{{PWD}}/cards/process/"
param_path = "{{PWD}}/cards/param/"

[madgraph]
params="1938"
nevents=10000

[madgraph.proc]
name = "ewksusy"

[madgraph.masses]

[pythia]
mpi = "off"

[analysis]
kfactor = 1.2
branchingratio = 1.0
